### ISSUE TITLE
[feature] 회원가입/로그인 기능

### ISSUE THREAD

**Issue by alwaysY0ung** [alwaysY0ung/Univ-Study-Manager#1]

**Comment by eun1337** [comment]
### [중간발표 전 상황보고] (may 25, 2024)
@eun1337 @alwaysY0ung @SoyunJung @eunseo0422 @rosy-n

- 실행화면
![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144989858/dd7725ff-57ee-4b9a-a4ae-cf71ffc4a86f)

![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144989858/3d8f959a-9b01-4b94-9a71-a579a81ded9f)

**구현 완료된 기능**
1. 로그인 기능(ID 및 PW 입력)
2. 회원가입 기능(ID 및 PW 입력)
3. 로그아웃 기능
4. 탈퇴 기능

**아직 구현 중인 기능**
1. '오늘의 일정&과제'창으로의 연결
2. 일부 예외 처리(아직 협의중에 있음.)
