### ISSUE TITLE
[feature] 오늘의 일정 & 과제

### ISSUE THREAD

**Issue by alwaysY0ung** [alwaysY0ung/Univ-Study-Manager#2]

**Comment by eunseo0422** [comment]
![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144988420/e794e089-e9ad-4bab-a652-c574546cac04)

![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144988420/9f428683-873d-46bf-b226-ba106d2219d6)
**구현 완료된 기능**
1. TO-DO Deadline
-사용자의 TO-DO 항목과 해당 항목의 완료 여부, 마감일을 표시하는 기능 구현
-JTable을 사용하여 TO-DO 항목을 표 형식으로 나타내며, 완료 여부는 체크박스로 표시
-체크박스의 상태에 따라 완료되지 않은 과제는 빨간색으로 강조기능 구현
2. 오늘 수업
-JTable을 사용하여 오늘 수업의 과목명, 진도 내용, 과제를 표시하는 기능 구현
3. 시간표 팝업 창
-JDialog를 통해 "시간표" 버튼을 클릭하면 시간표를 표시하는 팝업 창이 나타나는 기능 구현
4. 예정된 과제
-예정된 과제의 과목, 과제명, 마감일을 표시하는 기능 구현
5. 정렬 및 필터 선택
-예정된 과제를 시간순 또는 과목순으로 정렬할 수 있는 기능 구현
-전과목, 전공과목, 교양과목으로 과제를 필터링할 수 있는 기능 구현
-미완료 과제, 완료 과제, 전체 과제를 선택하여 표시할 수 있는 기능 구현
-과제의 종류(시험, 보고서, 퀴즈, 프로젝트)를 선택하여 표시할 수 있는 기능 구현
-JComboBox를 사용하여 정렬 및 필터 옵션을 선택할 수 있도록 함
6. 예정된 TO-DO
예정된 TO-DO 항목을 표시하는 패널 구현
7. 창 분할
-JSplitPane을 사용하여 프로그램 창을 좌우 및 상하로 분할하는 기능 구현
좌측에는 TO-DO Deadline과 오늘 수업을, 우측에는 예정된 과제와 예정된 TO-DO를 표시
-사용자는 분할 경계를 드래그하여 패널 크기를 조절 가능

**아직 구현 중인 기능**
1.데이터베이스와 연동하여 실제 일정 및 과제 데이터를 가져와 표시하는 기능 구현 예정
