### ISSUE TITLE
[feature] 수업DB

### ISSUE THREAD

**Issue by alwaysY0ung** [alwaysY0ung/Univ-Study-Manager#3]

**Comment by alwaysY0ung** [comment]
1. line81 '관련 파일' 논의 필요 (담당자 간 기능명세 통일 필요)
2. '복습'에 체크되어있지 않은 경우 빨간색으로 강조 표시 (주제발표ppt 준비시 협의된 사항. 다만 어느 부분을 빨간색으로 강조한다는 것인지 불분명)
3. '과목 추가' 기능 상세 구현 필요
4. To-Do를 팝업으로 띄울 수 있게 했는데 그대로 갈지
5. '예고된 강의 내용' 또한 누르면 팝업으로 뜨게 할지 (몰랐는데 생각보다 string이 길다)

**Comment by alwaysY0ung** [comment]
=> 해결된 논의사항 (may 24, 2024) @eun1337 @SoyunJung 

2. => 수업일이 오늘 당일이거나 지난날인 경우 빨간색으로 강조 표시 (java time LocalData불러서 처리할 것)
4. => To-Do 내용이 많이 않으므로 팝업으로 띄우는 것은 생략
5. => To-Do 내용 대신 정보량이 많은 '예고된 강의 내용' 부분을 팝업으로 띄우는 것으로 결정

**Comment by alwaysY0ung** [comment]
# [중간발표 전 상황보고] (may 25, 2024) @eun1337 @alwaysY0ung @SoyunJung @eunseo0422 @rosy-n 

## 수업DB에 대한 보고
- 실행화면 
![Uploading image.png…]()


### 구현 완료된 기능

1. csv파일에 저장된 데이터를 과목명을 기준으로 JTable 표시
2. JTable의 특정 열에 대한 렌더링을 사용자 정의
  1. "관련파일" 하이퍼링크 형식 표시. 클릭 시 URL 열림
  2. "예고된 강의 내용"은 클릭 시 상세 정보를 팝업으로 표시
  3. "수업일"이 당일이거나 전날인 경우, "복습" 체크박스가 미체크 상태라면 "예고된 강의 내용" 열의 글자색이 빨간색으로 표시
3. 마우스 이벤트 처리
  1. JTable의 셀을 클릭하면 해당 열에 따라 URL을 열거나 상세 정보를 팝업으로 표시


### 아직 구현 중인 기능
1. "완료여부" 체크박스가 미체크 상태라면 "To-Do" 열의 글자색이 빨간색으로 표시 (현재 작동하지 않음)
2. 마우스 이벤트 처리
  1. "+" 탭을 클릭하면 새로운 강의를 추가 (다이얼로그 나타내기, 테이블 추가하기까지만 구현)

- - -

## 그 외 논의된 사항 보고

- 수업DB 기능뿐만 아니라, 다른 소스코드들도 주석을 적극적으로 사용 권고
- 참고차 수업DB 소스코드 (test/DbGUI/ClassDb.java)에 주석을 작성했으니 정도에 대한 감을 잡으시길 바람
cf. 노션에 있는 '코드 내 주석' 
![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/160698032/bb02e938-7550-4507-9758-be4f43993554)

**Comment by SoyunJung** [comment]
# [중간발표 전 상황보고] (may 25, 2024)
@eun1337 @alwaysY0ung @SoyunJung @eunseo0422 @rosy-n

- 실행화면
![스크린샷 2024-05-25 183408](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/163826084/7bbda436-976c-4b36-92e1-79a75c7026cb)
![스크린샷 2024-05-25 183416](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/163826084/54c92080-6729-4d5a-bd7c-bf7034745b63)


**구현 완료된 기능**
1. csv파일에 저장된 데이터를 과목명을 기준으로 탭을 분할해 JTable 표시
2. JTable의 특정 열(column)에 대한 렌더링을 사용자 정의해 취사선택해 표시
3. "관련URL" 하이퍼링크 형식 표시.
4. "정보"는 클릭 시 csv의 "정보" 열의 내용을 정보를 팝업으로 표시
5. JTable의 셀을 클릭하면 해당 열에 따라 URL을 열거나 상세 정보를 팝업으로 표시

 +'정보'의 긴 string 불러오는 관정에서 \n등의 공백과 쉼표로 발생하는 오류 해결됨

**아직 구현 중인 기능**
1. "마감일"이 당일이거나 전날인 경우, "완료" 체크박스가 미체크 상태라면 "예고된 강의 내용" 열의 글자색이 빨간색으로 표시
2. "+" 탭을 클릭하면 새로운 강의를 추가 (다이얼로그 나타내기, 테이블 추가하기까지만 구현)
이는 '과제 DB와 수업 DB에서 모두 가능하고, 한쪽에서 추가한다면 다른 쪽에도 반영이 되도록' 구현하는 것이 좋아보임
3. 변동사항을 csv파일에 저장하는 기능
4. 기준에 따른 필터 기능
5. 기준에 따른 정렬 기능

**Comment by SoyunJung** [comment]
수업 DB랑 과제 DB랑 공유하는 class가 많고,

과제 DB에서는 DB + 과제 완료율에 따라 성장하는 나무
![스크린샷 2024-05-25 224720](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/163826084/6ba55161-a48d-42b4-9d13-de167e328ee5)
+ 팝업 3종류 (캘린더 포함)이고
![스크린샷 2024-05-25 224731](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/163826084/f4a5c4a2-3bf8-46bd-a451-1d2230a6d88d)
주제발표 준비하면서 보니  캘린더에는 인원이 아무도 배정되지 않았던데


아예 과제DB의 Jtable 부분을 수업DB의 Jtable 팀에서 같이 개발하고
기존 과제DB팀은 나무랑 저 캘린더팝업/블럭형팝업/Jtable형팝업(이건 과제DB팀에서 완성되면 정렬만 바꿔서 구현)하는 건 어떤가요?

이러면 Jtable 구현 소통도 원활하고 캘린더뷰/기타팝업 구현인원도 해결되고 업무량도 균등하게 나눠질 것 같습니다!
중간발표 이후에 같이 이야기해서 정해봐요

**Comment by alwaysY0ung** [comment]
> 아예 과제DB의 Jtable 부분을 수업DB의 Jtable 팀에서 같이 개발하고 기존 과제DB팀은 나무랑 저 캘린더팝업/블럭형팝업/Jtable형팝업 구현하는 건 어떤가요?

그렇게 했을 때 일정에 맞추어 구현될 수 있음이 확인되면 전 좋은 방법이라고 생각합니다

**Comment by alwaysY0ung** [comment]
# 건의사항
## git pull했을 때 실행환경이 다른 pc의 절대경로로 인해 매번 수정해야하는 번거로움이 있습니다. 상대경로로 수정함을 건의합니다.

**Comment by SoyunJung** [comment]
과제 DB에 구현한 기능
-변경사항 있으면 csv 파일에 반영(저장)하는 기능
-과제명 누르면 팝업으로 과제명 풀네임 볼 수 있는 기능
-2주 이후 시점보다 마감일이 이전시점인 경우 빨간색으로 강조표시
-과제종류는 JComboBox로 구현해서 선택지에서 선택할 수 있고 색깔로 구별함
-내 점수 열에서 적절한 점수 넣으면  "성적비율" "내 점수" "과제만점" 이 변경됨에 따라 "성적비율" * "내 점수" / "과제만점"로 "환산점수" 계산하고 업데이트하는 기능 구현
- '관련파일'열 칸에서 Jfilechooser로 파일 교체, 추가, 열기 구현
- '관련URL'열 칸에서 하이퍼링크 클릭하면 해당 링크 실행
- '정보'열 칸 클릭하면 관련정보 팝업으로 표시
이 있습니다

 수업 db에서도 필요한 기능이라면 코드 가져가서 쓰세요!
