### ISSUE TITLE
[feature] 자율계산기

### ISSUE THREAD

**Issue by alwaysY0ung** [alwaysY0ung/Univ-Study-Manager#6]

**Comment by eunseo0422** [comment]
![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144988420/c4d4efa9-1e33-4724-8ac0-d98ab3bed9e6)
![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144988420/90fa3985-957b-4b2b-9e84-465241a201a3)
![image](https://github.com/alwaysY0ung/Univ-Study-Manager/assets/144988420/937c30a3-0c0e-493e-8a9a-0d613b9b90b5)

**구현 완료된 기능**
1. 실시간 계산 내역 표시
-사용자가 수행한 계산 내역을 화면 우측에 실시간으로 표시하는 기능
-계산 내역이 길어질 경우, 스크롤을 통해 모든 계산 내역을 파악 가능
2. 오류 상황 처리
-잘못된 수식 입력(루트 안에 음수)이나 0으로 나누기 등의 오류 상황 발생 시, 계산기에서 해당 오류 부분을 출력
-사용자에게 명확한 피드백을 제공하여 오류 상황을 인지할 수 있도록 구현
3. 버튼 색상 구분
-숫자 버튼과 기능 버튼을 색상으로 구분하여 사용자의 편의성 향상
4. 패널 크기 조절
-계산기 패널과 계산 내역을 나타내는 패널의 사이즈를 사용자가 자유롭게 조절할 수 있도록 구현

**아직 구현 중인 기능**
1. 계산기 창과 노트 창 분리 기능
-사용자가 계산기와 노트를 동시에 사용할 수 있도록 하여 편의성을 향상시킬 수 있도록 하는 것이 목표
